// <auto-generated />
using System;
using BPA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BPA.Migrations
{
    [DbContext(typeof(BPADbContext))]
    [Migration("20250701082847_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("BPA.Models.BloodPressureRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Diastolic")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeartRate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Systolic")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BloodPressureRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
